node{

checkout scm;
def prop=readProperties  file: 'Properties/pipeline.properties'

stage('util clone')

{
def giturl=prop.UTIL_REPO_URL
echo "${giturl}"
git url:"${giturl}"
echo "cloned successfully"
}
}
