node{

checkout scm;
def prop=readProperties  file: 'Properties/pipeline.properties'

stage('util clone')

{

deleteDir()
sh prop.UTIL_REPO_URL
echo "cloned successfully"
def utilrepo=load "Util_Repository/dev_cicd.groovy"
utilrepo.execute();  
}
}
